export const mockDashboardResponse = {
  summary: {
    totalCurrentStock: 4800,
    totalAvailableStock: 4062,
    criticalSkuCount: 5,
    warningSkuCount: 7,
    riskAndWarningSkuCount: 12,
    shortageSkuCount: 9,
    expectedDisposalQty: 519,
  },
  warehouses: [
    {
      warehouseId: 1,
      warehouseCode: 'SEONGNAM',
      warehouseName: '성남 스마트푸드센터',
      regionCode: 'GYEONGGI',
      address: '경기도 성남시',
      currentStock: 956,
      availableStock: 872,
      nearExpiryStock: 68,
      outboundStock: 84,
      riskSkuCount: 5,
    },
  ],
  onlineSalesPoints: [
    {
      salesPointId: 10,
      salesPointCode: 'GREETING',
      salesPointName: '그리팅몰',
      regionCode: 'ONLINE',
      address: null,
      storageWarehouseCount: 2,
      currentStock: 912,
      availableStock: 833,
      nearExpiryStock: 74,
      expectedDisposalQty: 118,
      riskSkuCount: 2,
    },
  ],
  offlineStores: [
    {
      salesPointId: 13,
      salesPointCode: 'DEPT_PANGYO',
      salesPointName: '판교점',
      regionCode: 'GYEONGGI',
      address: '경기도 성남시',
      currentStock: 526,
      availableStock: 472,
      nearExpiryStock: 45,
      expectedDisposalQty: 38,
      riskSkuCount: 3,
    },
  ],
  riskSalesPointsTop10: [
    {
      rank: 1,
      salesPointId: 10,
      salesPointCode: 'GREETING',
      salesPointName: '그리팅몰',
      channelType: 'ONLINE',
      regionCode: 'ONLINE',
      availableStock: 833,
      riskSkuCount: 5,
      expectedDisposalQty: 118,
      nearExpiryStock: 74,
    },
  ],
  urgentSkusTop5: [
    {
      rank: 1,
      skuId: 7,
      skuCode: 'GF-SAL-GRN-05',
      skuName: '그린믹스 · 5팩',
      stockLocationType: 'WAREHOUSE',
      stockLocationId: 1,
      stockLocationCode: 'SEONGNAM',
      stockLocationName: '성남 스마트푸드센터',
      allocatedSalesPointCode: 'GREETING',
      allocatedSalesPointName: '그리팅몰',
      expiryDaysLeft: 12,
      saleStopDaysLeft: 5,
      expectedDisposalQty: 86,
      reasonMessage: '소비기한 내 판매 소진이 어렵습니다.',
    },
  ],
  calculatedAt: '2026-08-15T01:05:00Z',
};
