const missing = (label, representative = false) => ({ label, value: null, emptyLabel: '미수집', representative });
const kpi = (label, value, unit = '', representative = false) => ({ label, value, unit, representative });

export const strategyExecutionFixtures = [
  {
    id: 101,
    number: 'STR-2026-0815-001',
    status: 'EXECUTING',
    product: {
      skuId: 1297,
      name: '비비고 왕교자 1.05kg',
      sku: 'SKU-MANDU-1050',
      imageUrl: 'https://image.thehyundai.com/9/5/9/00/B0/40B0009597_0.jpg',
    },
    establishedAt: '2026-08-01',
    progress: 68,
    goal: '지역별 재고 편중을 완화하고 판매 속도가 높은 온라인 채널에 가용재고를 집중합니다.',
    resultSummary: '재할당 1건이 완료되었으며 채널 집중 액션이 진행 중입니다.',
    actions: [
      {
        id: 1001,
        type: 'REALLOCATION',
        title: '수도권 온라인 판매처 재할당',
        target: '경기 광주센터 → 그리팅몰',
        relationship: 'PARALLEL',
        dependsOn: [],
        status: 'COMPLETED',
        progress: 100,
        note: '안전재고 320개를 제외한 이동 가능 수량 내에서 실행되었습니다.',
        kpis: [
          kpi('요청 수량', 480, '개'),
          kpi('완료 수량', 480, '개', true),
          kpi('가용재고 증가', 480, '개'),
          kpi('완료율', 100, '%'),
          kpi('재고 편중도 변화', -12, '%p'),
        ],
      },
      {
        id: 1002,
        type: 'CHANNEL_CONCENTRATION',
        title: '그리팅몰 채널 집중',
        target: '그리팅몰',
        relationship: 'SEQUENTIAL',
        dependsOn: [1001],
        status: 'IN_PROGRESS',
        progress: 36,
        kpis: [
          kpi('집중 채널 배정', 480, '개'),
          kpi('집중 채널 판매량', 173, '개', true),
          kpi('판매 비중', 41, '%'),
          kpi('재고 회전율 변화', 0.4, '회'),
          kpi('재고 배분 효과', 160, '개'),
          kpi('축소 채널 품절 위험', '낮음'),
        ],
      },
    ],
    inventoryResults: [
      { location: '경기 광주센터', before: 2310, moved: -480, after: 1830, guardrail: '안전재고 320개 유지' },
      { location: '그리팅몰', before: 190, moved: 480, after: 670, guardrail: '가용재고 증가' },
    ],
    inventoryTransfers: [
      {
        fromLocationId: 7,
        fromLocationName: '경기 광주센터',
        toLocationId: 3,
        toLocationName: '그리팅몰',
        destinationWarehouseId: 13,
        destinationWarehouseName: '그리팅 물류센터',
        targetSalesPointId: 3,
        targetSalesPointName: '그리팅몰',
        quantity: 480,
      },
    ],
    channelResults: [
      { channel: '그리팅몰', status: '집중 운영', sales: 173, revenue: '1,384만원', cannibalization: '해당 없음' },
      { channel: '더현대서울', status: '유지', sales: 96, revenue: '768만원', cannibalization: '관찰 중' },
    ],
    salesDaily: [
      { date: '2026-08-01', salesPoint: '그리팅몰', quantity: 12 },
      { date: '2026-08-02', salesPoint: '그리팅몰', quantity: 15 },
      { date: '2026-08-03', salesPoint: '그리팅몰', quantity: 17 },
      { date: '2026-08-04', salesPoint: '그리팅몰', quantity: 14 },
      { date: '2026-08-05', salesPoint: '그리팅몰', quantity: 16 },
      { date: '2026-08-06', salesPoint: '그리팅몰', quantity: 18 },
      { date: '2026-08-07', salesPoint: '그리팅몰', quantity: 20 },
      { date: '2026-08-08', salesPoint: '그리팅몰', quantity: 19 },
      { date: '2026-08-09', salesPoint: '그리팅몰', quantity: 21 },
      { date: '2026-08-10', salesPoint: '그리팅몰', quantity: 21 },
      { date: '2026-08-01', salesPoint: '더현대서울', quantity: 8 },
      { date: '2026-08-02', salesPoint: '더현대서울', quantity: 9 },
      { date: '2026-08-03', salesPoint: '더현대서울', quantity: 10 },
      { date: '2026-08-04', salesPoint: '더현대서울', quantity: 9 },
      { date: '2026-08-05', salesPoint: '더현대서울', quantity: 11 },
      { date: '2026-08-06', salesPoint: '더현대서울', quantity: 8 },
      { date: '2026-08-07', salesPoint: '더현대서울', quantity: 10 },
      { date: '2026-08-08', salesPoint: '더현대서울', quantity: 9 },
      { date: '2026-08-09', salesPoint: '더현대서울', quantity: 11 },
      { date: '2026-08-10', salesPoint: '더현대서울', quantity: 11 },
    ],
    salesPointComparison: [
      { salesPoint: '그리팅몰', role: 'DESTINATION', label: '이동 대상 판매처' },
      { salesPoint: '더현대서울', role: 'SOURCE', label: '기존 판매처' },
    ],
    performance: {
      actualSalesQuantity: 269,
      actualRevenue: 21520000,
      actualContributionMargin: 6840000,
      actualRemainingQuantity: 401,
    },
    lastSyncedAt: '2026-08-15T08:42:00+09:00',
  },
  {
    id: 102,
    number: 'STR-2026-0814-014',
    status: 'PARTIAL',
    product: { skuId: 2002, name: '프리미엄 오피스 체어 에어', sku: 'SKU-CHAIR-AIR', imageUrl: null },
    establishedAt: '2026-08-02',
    progress: 42,
    goal: '서부권 재고를 동부권으로 이동한 뒤 신규 B2B 채널을 개설합니다.',
    resultSummary: '재고 재할당은 일부 완료되었으나 RT 이동 실패로 후행 채널 확장이 차단되었습니다.',
    actions: [
      {
        id: 2001,
        type: 'REALLOCATION',
        title: '서부 물류센터 재고 재할당',
        target: '서부센터 → 동부센터',
        relationship: 'PARALLEL',
        dependsOn: [],
        status: 'PARTIAL',
        progress: 75,
        kpis: [
          kpi('요청 수량', 120, '개'),
          kpi('완료 수량', 90, '개', true),
          kpi('가용재고 증가', 90, '개'),
          kpi('완료율', 75, '%'),
          kpi('재고 편중도 변화', -8, '%p'),
        ],
      },
      {
        id: 2002,
        type: 'RT_TRANSFER',
        title: '동부권 RT 이동',
        target: '서부센터 → 동부센터',
        relationship: 'SEQUENTIAL',
        dependsOn: [2001],
        status: 'FAILED',
        progress: 25,
        note: '운송사 배차가 취소되어 입고가 완료되지 않았습니다.',
        kpis: [
          kpi('이동 요청', 90, '개'),
          kpi('출고 완료', 90, '개'),
          kpi('입고 완료', 0, '개', true),
          kpi('이동 중', 90, '개'),
          kpi('이동 완료율', 0, '%'),
          kpi('지연 시간', 19, '시간'),
        ],
      },
      {
        id: 2003,
        type: 'CHANNEL_EXPANSION',
        title: '동부 B2B 채널 확장',
        target: '동부권 기업복지몰',
        relationship: 'CONDITIONAL',
        dependsOn: [2002],
        status: 'BLOCKED',
        progress: 0,
        note: '선행 RT 이동 실패로 실행이 차단되었습니다.',
        kpis: [
          missing('신규 채널 개설', true),
          missing('신규 채널 배정'),
          missing('신규 채널 판매량'),
          missing('신규 채널 매출'),
          missing('전체 판매량 증가'),
          missing('기존 채널 잠식 여부'),
        ],
      },
    ],
    inventoryResults: [
      { location: '서부센터', before: 340, moved: -90, after: 250, guardrail: '안전재고 180개 유지' },
      { location: '동부센터', before: 34, moved: 90, after: null, guardrail: '입고 미완료' },
    ],
    inventoryTransfers: [
      {
        fromLocationId: 11,
        fromLocationName: '서부센터',
        toLocationId: 12,
        toLocationName: '동부센터',
        destinationWarehouseId: 12,
        destinationWarehouseName: '동부센터',
        targetSalesPointId: null,
        targetSalesPointName: null,
        quantity: 90,
      },
    ],
    channelResults: [],
    salesDaily: [],
    salesPointComparison: [],
    performance: null,
    lastSyncedAt: '2026-08-15T07:20:00+09:00',
  },
  {
    id: 103,
    number: 'STR-2026-0815-022',
    status: 'READY',
    product: {
      skuId: 2438,
      name: '그리팅 저당 도시락 6종',
      sku: 'SKU-GRT-MEAL-06',
      imageUrl: 'https://image.greating.co.kr/IL/item/202607/01/B_694004AB11044B58BD12C1104A654D62.jpg',
    },
    establishedAt: '2026-08-15',
    progress: 0,
    goal: '서로 다른 판매처에 동일 재할당 액션을 병렬 실행해 초기 재고를 균등 배치합니다.',
    resultSummary: '실행 요청 전이며 성과 데이터가 아직 수집되지 않았습니다.',
    actions: [
      {
        id: 3001,
        type: 'REALLOCATION',
        title: '강남점 초기 재할당',
        target: '성남센터 → 강남점',
        relationship: 'PARALLEL',
        dependsOn: [],
        status: 'NOT_STARTED',
        progress: 0,
        kpis: [
          kpi('요청 수량', 80, '개'),
          missing('완료 수량', true),
          missing('가용재고 증가'),
          missing('완료율'),
          missing('재고 편중도 변화'),
        ],
      },
      {
        id: 3002,
        type: 'REALLOCATION',
        title: '송도점 초기 재할당',
        target: '성남센터 → 송도점',
        relationship: 'PARALLEL',
        dependsOn: [],
        status: 'NOT_STARTED',
        progress: 0,
        kpis: [
          kpi('요청 수량', 65, '개'),
          missing('완료 수량', true),
          missing('가용재고 증가'),
          missing('완료율'),
          missing('재고 편중도 변화'),
        ],
      },
    ],
    inventoryResults: [],
    inventoryTransfers: [],
    channelResults: [],
    salesDaily: [],
    salesPointComparison: [],
    performance: null,
    lastSyncedAt: null,
  },
  {
    id: 104,
    number: 'STR-2026-0812-006',
    status: 'COMPLETED',
    product: { skuId: 4004, name: '산지직송 샤인머스캣 2kg', sku: 'SKU-FRUIT-SM2', imageUrl: null },
    establishedAt: '2026-07-01',
    progress: 100,
    goal: '온라인 신규 채널을 열고 성과가 높은 채널로 잔여 재고를 집중합니다.',
    resultSummary: '채널 확장과 집중 액션이 모두 완료되었으며 최신 판매 성과가 반영되었습니다.',
    actions: [
      {
        id: 4001,
        type: 'CHANNEL_EXPANSION',
        title: '식품관 투홈 채널 개설',
        target: '현대식품관 투홈',
        relationship: 'SEQUENTIAL',
        dependsOn: [],
        status: 'COMPLETED',
        progress: 100,
        kpis: [
          kpi('신규 채널 개설', '완료', '', true),
          kpi('신규 채널 배정', 240, '개'),
          kpi('신규 채널 판매량', 218, '개'),
          kpi('신규 채널 매출', 1526, '만원'),
          kpi('전체 판매량 증가', 18, '%'),
          kpi('기존 채널 잠식 여부', '없음'),
        ],
      },
      {
        id: 4002,
        type: 'CHANNEL_CONCENTRATION',
        title: '투홈 잔여 재고 집중',
        target: '현대식품관 투홈',
        relationship: 'SEQUENTIAL',
        dependsOn: [4001],
        status: 'COMPLETED',
        progress: 100,
        kpis: [
          kpi('집중 채널 배정', 120, '개'),
          kpi('집중 채널 판매량', 117, '개', true),
          kpi('판매 비중', 54, '%'),
          kpi('재고 회전율 변화', 1.2, '회'),
          kpi('재고 배분 효과', 28, '%'),
          kpi('축소 채널 품절 위험', '낮음'),
        ],
      },
    ],
    inventoryResults: [
      { location: '온라인 통합재고', before: 360, moved: -360, after: 0, guardrail: '시즌 종료 상품' },
    ],
    inventoryTransfers: [],
    channelResults: [
      {
        channel: '현대식품관 투홈',
        status: '판매 완료',
        sales: 335,
        revenue: '2,345만원',
        cannibalization: '해당 없음',
      },
    ],
    salesDaily: [],
    salesPointComparison: [],
    performance: {
      actualSalesQuantity: 335,
      actualRevenue: 23450000,
      actualContributionMargin: 7120000,
      actualRemainingQuantity: 0,
    },
    lastSyncedAt: '2026-08-15T09:10:00+09:00',
  },
];
