export const distributionCenters = Object.freeze([
  {
    id: 'GYEONGIN_1',
    name: '경인센터 1',
    shortName: '경인1',
    region: '수도권',
    description: '수도권 판매처 공급',
    x: 24,
    y: 24,
    currentStock: 768,
    availableStock: 694,
    nearExpiryStock: 42,
    outboundStock: 74,
    riskSkuCount: 4,
  },
  {
    id: 'GYEONGIN_2',
    name: '경인센터 2',
    shortName: '경인2',
    region: '수도권',
    description: '수도권 판매처 공급',
    x: 18,
    y: 43,
    currentStock: 492,
    availableStock: 438,
    nearExpiryStock: 35,
    outboundStock: 54,
    riskSkuCount: 3,
  },
  {
    id: 'SUJI',
    name: '용인-수지센터',
    shortName: '수지',
    region: '수도권',
    description: '유통상품 전용',
    x: 38,
    y: 37,
    currentStock: 410,
    availableStock: 366,
    nearExpiryStock: 12,
    outboundStock: 44,
    riskSkuCount: 2,
  },
  {
    id: 'SEONGNAM',
    name: '성남 스마트푸드센터',
    shortName: '성남',
    region: '수도권',
    description: '그리팅 상품 생산·공급',
    x: 49,
    y: 20,
    currentStock: 956,
    availableStock: 872,
    nearExpiryStock: 68,
    outboundStock: 84,
    riskSkuCount: 5,
  },
  {
    id: 'DONGTAN',
    name: '동탄센터',
    shortName: '동탄',
    region: '수도권',
    description: '경기 남부 판매처 공급',
    x: 52,
    y: 50,
    currentStock: 526,
    availableStock: 472,
    nearExpiryStock: 29,
    outboundStock: 54,
    riskSkuCount: 3,
  },
  {
    id: 'ICHEON_DC',
    name: '이천 DC',
    shortName: '이천',
    region: '수도권',
    description: '광역 배분·이동 거점',
    x: 70,
    y: 37,
    currentStock: 598,
    availableStock: 536,
    nearExpiryStock: 31,
    outboundStock: 62,
    riskSkuCount: 2,
  },
  {
    id: 'YEONGNAM',
    name: '영남센터',
    shortName: '영남',
    region: '영남권',
    description: '영남권 판매처 공급',
    x: 76,
    y: 72,
    currentStock: 366,
    availableStock: 322,
    nearExpiryStock: 57,
    outboundStock: 44,
    riskSkuCount: 6,
  },
  {
    id: 'HONAM',
    name: '호남센터',
    shortName: '호남',
    region: '호남권',
    description: '호남권 판매처 공급',
    x: 39,
    y: 78,
    currentStock: 401,
    availableStock: 362,
    nearExpiryStock: 12,
    outboundStock: 39,
    riskSkuCount: 2,
  },
]);

export const riskSalesPoints = Object.freeze([
  {
    id: 'MODU',
    name: '모두의 맛집',
    type: '온라인',
    region: '전국',
    availableStock: 214,
    riskSkuCount: 1,
    expectedDisposal: 52,
  },
  {
    id: 'THE_HYUNDAI_SEOUL',
    name: '더현대 서울 식품관',
    type: '오프라인',
    region: '서울',
    availableStock: 406,
    riskSkuCount: 2,
    expectedDisposal: 42,
  },
  {
    id: 'PANGYO',
    name: '현대백화점 판교점 식품관',
    type: '오프라인',
    region: '경기',
    availableStock: 472,
    riskSkuCount: 3,
    expectedDisposal: 38,
  },
  {
    id: 'HMART',
    name: 'H마트',
    type: '오프라인',
    region: '수도권',
    availableStock: 189,
    riskSkuCount: 1,
    expectedDisposal: 36,
  },
  {
    id: 'GREETING',
    name: '그리팅몰',
    type: '온라인',
    region: '전국',
    availableStock: 833,
    riskSkuCount: 2,
    expectedDisposal: 118,
  },
]);

export const urgentSkus = Object.freeze([
  {
    id: 'GF-SKU-005',
    code: 'GF-SOUP-CHK-06',
    name: '닭곰탕 · 6팩',
    salesPoint: '모두의 맛집',
    riskScore: 82.8,
    expiryDays: 31,
    expectedDisposal: 27,
    issue: '회전 저하',
  },
  {
    id: 'GF-SKU-007',
    code: 'GF-SAL-GRN-05',
    name: '그린믹스 · 5팩',
    salesPoint: '그리팅몰',
    riskScore: 96.4,
    expiryDays: 12,
    expectedDisposal: 86,
    issue: '폐기 위험',
  },
  {
    id: 'GF-SKU-001',
    code: 'GF-LUNCH-BEEF-350',
    name: '소불고기 도시락 · 350g',
    salesPoint: '더현대 서울 식품관',
    riskScore: 86.3,
    expiryDays: 24,
    expectedDisposal: 35,
    issue: '판매 부진',
  },
  {
    id: 'GF-SKU-009',
    code: 'GF-LUNCH-CHK-350',
    name: '닭가슴살 현미 도시락 · 350g',
    salesPoint: '현대백화점 판교점 식품관',
    riskScore: 89.7,
    expiryDays: 20,
    expectedDisposal: 42,
    issue: '장기 보유',
  },
  {
    id: 'GF-SKU-003',
    code: 'GF-LUNCH-TOFU-350',
    name: '두부버섯 도시락 · 350g',
    salesPoint: '그리팅몰',
    riskScore: 92.1,
    expiryDays: 18,
    expectedDisposal: 64,
    issue: '소진 지연',
  },
]);

export const dashboardInventorySummary = Object.freeze({
  totalAvailableStock: distributionCenters.reduce((sum, center) => sum + center.availableStock, 0),
  riskAndCautionSkuCount: 12,
  shortageSkuCount: 9,
  expectedDisposal: riskSalesPoints.reduce((sum, point) => sum + point.expectedDisposal, 0),
});

export function rankRiskSalesPoints(points = riskSalesPoints) {
  return [...points].sort(
    (left, right) =>
      right.riskSkuCount - left.riskSkuCount ||
      right.expectedDisposal - left.expectedDisposal ||
      left.name.localeCompare(right.name, 'ko'),
  );
}

export function rankUrgentSkus(skus = urgentSkus) {
  return [...skus].sort(
    (left, right) =>
      right.riskScore - left.riskScore ||
      right.expectedDisposal - left.expectedDisposal ||
      left.name.localeCompare(right.name, 'ko'),
  );
}
