export const distributionCenters = Object.freeze([
  {
    id: 'GYEONGIN_1',
    name: '경인센터 1',
    shortName: '경인1',
    region: '수도권',
    description: '수도권 판매처 공급',
    x: 24,
    y: 24,
    currentStock: 768,
    availableStock: 694,
    nearExpiryStock: 42,
    outboundStock: 74,
    riskSkuCount: 4,
  },
  {
    id: 'GYEONGIN_2',
    name: '경인센터 2',
    shortName: '경인2',
    region: '수도권',
    description: '수도권 판매처 공급',
    x: 18,
    y: 43,
    currentStock: 492,
    availableStock: 438,
    nearExpiryStock: 35,
    outboundStock: 54,
    riskSkuCount: 3,
  },
  {
    id: 'SUJI',
    name: '용인-수지센터',
    shortName: '수지',
    region: '수도권',
    description: '유통상품 전용',
    x: 38,
    y: 37,
    currentStock: 410,
    availableStock: 366,
    nearExpiryStock: 12,
    outboundStock: 44,
    riskSkuCount: 2,
  },
  {
    id: 'SEONGNAM',
    name: '성남 스마트푸드센터',
    shortName: '성남',
    region: '수도권',
    description: '그리팅 상품 생산·공급',
    x: 49,
    y: 20,
    currentStock: 956,
    availableStock: 872,
    nearExpiryStock: 68,
    outboundStock: 84,
    riskSkuCount: 5,
  },
  {
    id: 'DONGTAN',
    name: '동탄센터',
    shortName: '동탄',
    region: '수도권',
    description: '경기 남부 판매처 공급',
    x: 52,
    y: 50,
    currentStock: 526,
    availableStock: 472,
    nearExpiryStock: 29,
    outboundStock: 54,
    riskSkuCount: 3,
  },
  {
    id: 'ICHEON_DC',
    name: '이천 DC',
    shortName: '이천',
    region: '수도권',
    description: '광역 배분·이동 거점',
    x: 70,
    y: 37,
    currentStock: 598,
    availableStock: 536,
    nearExpiryStock: 31,
    outboundStock: 62,
    riskSkuCount: 2,
  },
  {
    id: 'YEONGNAM',
    name: '영남센터',
    shortName: '영남',
    region: '영남권',
    description: '영남권 판매처 공급',
    x: 76,
    y: 72,
    currentStock: 366,
    availableStock: 322,
    nearExpiryStock: 57,
    outboundStock: 44,
    riskSkuCount: 6,
  },
  {
    id: 'HONAM',
    name: '호남센터',
    shortName: '호남',
    region: '호남권',
    description: '호남권 판매처 공급',
    x: 39,
    y: 78,
    currentStock: 401,
    availableStock: 362,
    nearExpiryStock: 12,
    outboundStock: 39,
    riskSkuCount: 2,
  },
]);

export const salesPointInventories = Object.freeze([
  {
    id: 'GREETING',
    code: 'GREETING',
    name: '그리팅몰',
    type: '온라인',
    region: '온라인',
    active: true,
    currentStock: 912,
    availableStock: 833,
    nearExpiryStock: 74,
    riskSkuCount: 2,
    expectedDisposal: 118,
  },
  {
    id: 'MODU_MATJIP',
    code: 'MODU_MATJIP',
    name: '모두의 맛집',
    type: '온라인',
    region: '온라인',
    active: true,
    currentStock: 246,
    availableStock: 214,
    nearExpiryStock: 31,
    riskSkuCount: 1,
    expectedDisposal: 52,
  },
  {
    id: 'DEPT_THEHYUNDAI_SEOUL',
    code: 'DEPT_THEHYUNDAI_SEOUL',
    name: '더현대 서울',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 25,
    y: 17,
    currentStock: 454,
    availableStock: 406,
    nearExpiryStock: 36,
    riskSkuCount: 2,
    expectedDisposal: 42,
  },
  {
    id: 'DEPT_APGUJEONG',
    code: 'DEPT_APGUJEONG',
    name: '압구정본점',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 39,
    y: 24,
    currentStock: 398,
    availableStock: 361,
    nearExpiryStock: 28,
    riskSkuCount: 2,
    expectedDisposal: 31,
  },
  {
    id: 'DEPT_TRADE_CENTER',
    code: 'DEPT_TRADE_CENTER',
    name: '무역센터점',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 53,
    y: 19,
    currentStock: 428,
    availableStock: 382,
    nearExpiryStock: 33,
    riskSkuCount: 2,
    expectedDisposal: 37,
  },
  {
    id: 'DEPT_CHEONHO',
    code: 'DEPT_CHEONHO',
    name: '천호점',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 66,
    y: 28,
    currentStock: 349,
    availableStock: 306,
    nearExpiryStock: 41,
    riskSkuCount: 3,
    expectedDisposal: 46,
  },
  {
    id: 'DEPT_SINCHON',
    code: 'DEPT_SINCHON',
    name: '신촌점',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 25,
    y: 34,
    currentStock: 287,
    availableStock: 254,
    nearExpiryStock: 25,
    riskSkuCount: 1,
    expectedDisposal: 22,
  },
  {
    id: 'DEPT_MIA',
    code: 'DEPT_MIA',
    name: '미아점',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 56,
    y: 8,
    currentStock: 316,
    availableStock: 278,
    nearExpiryStock: 32,
    riskSkuCount: 2,
    expectedDisposal: 34,
  },
  {
    id: 'DEPT_MOKDONG',
    code: 'DEPT_MOKDONG',
    name: '목동점',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 16,
    y: 46,
    currentStock: 386,
    availableStock: 342,
    nearExpiryStock: 39,
    riskSkuCount: 3,
    expectedDisposal: 44,
  },
  {
    id: 'DEPT_JUNGDONG',
    code: 'DEPT_JUNGDONG',
    name: '중동점',
    type: '오프라인',
    region: '경기',
    active: true,
    x: 24,
    y: 55,
    currentStock: 302,
    availableStock: 268,
    nearExpiryStock: 27,
    riskSkuCount: 1,
    expectedDisposal: 24,
  },
  {
    id: 'DEPT_KINTEX',
    code: 'DEPT_KINTEX',
    name: '킨텍스점',
    type: '오프라인',
    region: '경기',
    active: true,
    x: 11,
    y: 27,
    currentStock: 331,
    availableStock: 294,
    nearExpiryStock: 30,
    riskSkuCount: 2,
    expectedDisposal: 29,
  },
  {
    id: 'DEPT_DCUBE',
    code: 'DEPT_DCUBE',
    name: '디큐브시티',
    type: '오프라인',
    region: '서울',
    active: false,
    x: 0,
    y: 0,
    currentStock: 0,
    availableStock: 0,
    nearExpiryStock: 0,
    riskSkuCount: 0,
    expectedDisposal: 0,
  },
  {
    id: 'DEPT_PANGYO',
    code: 'DEPT_PANGYO',
    name: '판교점',
    type: '오프라인',
    region: '경기',
    active: true,
    x: 48,
    y: 41,
    currentStock: 526,
    availableStock: 472,
    nearExpiryStock: 45,
    riskSkuCount: 3,
    expectedDisposal: 38,
  },
  {
    id: 'DEPT_BUSAN',
    code: 'DEPT_BUSAN',
    name: '커넥트현대 부산',
    type: '오프라인',
    region: '부산',
    active: true,
    x: 82,
    y: 78,
    currentStock: 273,
    availableStock: 238,
    nearExpiryStock: 31,
    riskSkuCount: 2,
    expectedDisposal: 33,
  },
  {
    id: 'DEPT_DAEGU',
    code: 'DEPT_DAEGU',
    name: '더현대 대구',
    type: '오프라인',
    region: '대구',
    active: true,
    x: 71,
    y: 63,
    currentStock: 421,
    availableStock: 376,
    nearExpiryStock: 37,
    riskSkuCount: 3,
    expectedDisposal: 41,
  },
  {
    id: 'DEPT_ULSAN',
    code: 'DEPT_ULSAN',
    name: '울산점',
    type: '오프라인',
    region: '울산',
    active: true,
    x: 88,
    y: 61,
    currentStock: 294,
    availableStock: 258,
    nearExpiryStock: 34,
    riskSkuCount: 2,
    expectedDisposal: 36,
  },
  {
    id: 'DEPT_CHUNGCHEONG',
    code: 'DEPT_CHUNGCHEONG',
    name: '충청점',
    type: '오프라인',
    region: '충청',
    active: true,
    x: 51,
    y: 58,
    currentStock: 318,
    availableStock: 281,
    nearExpiryStock: 29,
    riskSkuCount: 1,
    expectedDisposal: 26,
  },
  {
    id: 'HMART_ASAN_HOSPITAL',
    code: 'HMART_ASAN_HOSPITAL',
    name: 'Hmart 아산병원점',
    type: '오프라인',
    region: '서울',
    active: true,
    x: 70,
    y: 12,
    currentStock: 218,
    availableStock: 189,
    nearExpiryStock: 27,
    riskSkuCount: 1,
    expectedDisposal: 36,
  },
]);

export const offlineStoreInventories = Object.freeze(
  salesPointInventories.filter((point) => point.type === '오프라인' && point.active),
);

export const onlineSalesPointInventories = Object.freeze(
  salesPointInventories
    .filter((point) => point.type === '온라인' && point.active)
    .map((point) => ({
      ...point,
      shortName: point.name,
      storageWarehouseCount: 1,
      x: point.code === 'GREETING' ? 34 : 66,
      y: point.code === 'GREETING' ? 44 : 56,
    })),
);

export const riskSalesPoints = offlineStoreInventories;

export const urgentSkus = Object.freeze([
  {
    id: 'GF-SKU-005',
    code: 'GF-SOUP-CHK-06',
    name: '닭곰탕 · 6팩',
    salesPoint: '모두의 맛집',
    riskScore: 82.8,
    expiryDays: 31,
    expectedDisposal: 27,
    issue: '회전 저하',
  },
  {
    id: 'GF-SKU-007',
    code: 'GF-SAL-GRN-05',
    name: '그린믹스 · 5팩',
    salesPoint: '그리팅몰',
    riskScore: 96.4,
    expiryDays: 12,
    expectedDisposal: 86,
    issue: '폐기 위험',
  },
  {
    id: 'GF-SKU-001',
    code: 'GF-LUNCH-BEEF-350',
    name: '소불고기 도시락 · 350g',
    salesPoint: '더현대 서울 식품관',
    riskScore: 86.3,
    expiryDays: 24,
    expectedDisposal: 35,
    issue: '판매 부진',
  },
  {
    id: 'GF-SKU-009',
    code: 'GF-LUNCH-CHK-350',
    name: '닭가슴살 현미 도시락 · 350g',
    salesPoint: '현대백화점 판교점 식품관',
    riskScore: 89.7,
    expiryDays: 20,
    expectedDisposal: 42,
    issue: '장기 보유',
  },
  {
    id: 'GF-SKU-003',
    code: 'GF-LUNCH-TOFU-350',
    name: '두부버섯 도시락 · 350g',
    salesPoint: '그리팅몰',
    riskScore: 92.1,
    expiryDays: 18,
    expectedDisposal: 64,
    issue: '소진 지연',
  },
]);

export const dashboardInventorySummary = Object.freeze({
  totalAvailableStock: distributionCenters.reduce((sum, center) => sum + center.availableStock, 0),
  criticalSkuCount: 5,
  warningSkuCount: 7,
  riskAndCautionSkuCount: 12,
  shortageSkuCount: 9,
  expectedDisposal: riskSalesPoints.reduce((sum, point) => sum + point.expectedDisposal, 0),
});

export function rankRiskSalesPoints(points = riskSalesPoints) {
  return [...points].sort(
    (left, right) =>
      right.riskSkuCount - left.riskSkuCount ||
      right.expectedDisposal - left.expectedDisposal ||
      left.name.localeCompare(right.name, 'ko'),
  );
}

export function rankUrgentSkus(skus = urgentSkus) {
  return [...skus].sort(
    (left, right) =>
      right.riskScore - left.riskScore ||
      right.expectedDisposal - left.expectedDisposal ||
      left.name.localeCompare(right.name, 'ko'),
  );
}
